version: "3.2"

networks:
  testnet:
    external:
      name: testnet

services:
  mysql:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == priyansh-Inspiron-3543
    image: mysql:latest
    command: docker-entrypoint.sh mysqld
    hostname: mysql
    container_name: mysql
    ports:
      - "3900:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
    networks:
      testnet:
        aliases:
          - mysql

  ecom_server:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == priyansh-Inspiron-3543
    image: iwp/local:apache
    command: /bin/bash -c "/usr/sbin/apache2ctl -D FOREGROUND"
    hostname: ecom_server
    working_dir: /var/www/html
    container_name: ecom_server
    environment:
      - ServerName=localhost
    volumes:
      - /var/www/html:/var/www/html
    ports:
      - "8080:80"
    networks:
      testnet:
        aliases:
          - apache
